# configure server port
server.port: 8081

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.format_sql: false
    show-sql: true
  h2.console.enabled: true # the JDBC URL is jdbc:h2:mem:testdb

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    # setup logging for transactions
    org.springframework.web: ERROR
    org.hibernate: ERROR
    com.sda.spring.boot.rest: INFO